//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int Id { get; set; }
        public string Dscription { get; set; }
        public System.DateTime NoteTimestamp { get; set; }
        public int Issueid { get; set; }
        public int SupervisorId { get; set; }
        public int SupporterId { get; set; }
    
        public virtual Issue1 Issue1 { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        public virtual Supporter Supporter { get; set; }
    }
}
